services:
  - type: web
    name: cappy-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cappy-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://your-netlify-app.netlify.app
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: cappy-db
    databaseName: cappy
    user: cappy
    plan: free 